// Builds subdivisions.json (shared with the frontend) and sql/seed.sql from one list,
// so the map and the database can't drift apart.
import fs from 'node:fs';

const rows = [
  ['Indiranagar', 'IND-01', 'East', 12.9784, 77.6408, 1.6, 'Older LT lines outside the core; transformer trips when heavy rain hits'],
  ['Koramangala', 'KOR-02', 'South', 12.9352, 77.6245, 3.1, 'Feeder loading in evening peak, planned Tuesday shutdowns'],
  ['Whitefield', 'WHF-03', 'East', 12.9698, 77.7500, 6.4, 'Overloaded feeders from fast apartment growth, monsoon tripping'],
  ['Hoodi', 'HOO-04', 'East', 12.9910, 77.7160, 5.6, 'Feeder overload on ITPL side, neutral breaks in heavy rain'],
  ['HSR Layout', 'HSR-05', 'South', 12.9116, 77.6389, 3.4, 'Tuesday maintenance windows, evening transformer loading'],
  ['Jayanagar', 'JAY-06', 'South', 12.9250, 77.5938, 1.4, 'Mostly underground network, rare tree-fall faults'],
  ['JP Nagar', 'JPN-07', 'South', 12.9063, 77.5857, 2.6, 'Planned Tuesday shutdowns, pockets of overhead lines'],
  ['Hebbal', 'HEB-08', 'North', 13.0358, 77.5970, 2.2, 'Overhead line faults near the flyover belt, planned maintenance'],
  ['Yelahanka', 'YEL-09', 'North', 13.1007, 77.5963, 5.3, 'Long overhead feeders, monsoon tripping, load growth'],
  ['Bellandur', 'BEL-10', 'East', 12.9260, 77.6762, 5.9, 'Waterlogging faults, overloaded apartment-cluster feeders'],
  ['Malleshwaram', 'MAL-11', 'North', 13.0035, 77.5643, 1.8, 'Old but well-maintained network, short planned shutdowns'],
  ['Electronic City', 'ELC-12', 'South', 12.8452, 77.6602, 2.9, 'Industrial load swings, Tuesday maintenance']
];

const risk = h => (h > 5 ? 'high' : h >= 2 ? 'medium' : 'low');
const color = { high: '#EF4444', medium: '#F59E0B', low: '#10B981' };
const ups = {
  high: '1500 VA inverter + 2 x 150Ah tubular battery',
  medium: '1100 VA inverter + 1 x 150Ah tubular battery',
  low: '850 VA inverter + 1 x 100Ah battery (optional)'
};

const out = rows.map(([name, code, zone, lat, lng, hrs, trig]) => {
  const level = risk(hrs);
  return {
    id: code, division_name: name, subdivision_code: code, zone,
    outage_risk_level: level, color_code: color[level],
    reliability_score: Math.max(0, Math.min(100, Math.round(100 - hrs * 8))),
    avg_weekly_outage_hours: hrs, recommended_ups: ups[level],
    latitude: lat, longitude: lng, grid_triggers: trig, boundary_coordinates: null
  };
});

fs.writeFileSync('frontend/src/subdivisions.json', JSON.stringify(out, null, 2));

const q = s => `'${String(s).replace(/'/g, "''")}'`;
const sql = out.map(r =>
  `insert into bescom_subdivisions (id, division_name, subdivision_code, zone, outage_risk_level, color_code, reliability_score, avg_weekly_outage_hours, recommended_ups, latitude, longitude, grid_triggers) values (${[
    q(r.id), q(r.division_name), q(r.subdivision_code), q(r.zone), q(r.outage_risk_level), q(r.color_code),
    r.reliability_score, r.avg_weekly_outage_hours, q(r.recommended_ups), r.latitude, r.longitude, q(r.grid_triggers)
  ].join(', ')}) on conflict (id) do update set avg_weekly_outage_hours = excluded.avg_weekly_outage_hours, outage_risk_level = excluded.outage_risk_level, color_code = excluded.color_code, reliability_score = excluded.reliability_score;`
).join('\n');

const rest = `
insert into bescom_tariff_rates (id, category, energy_rate, fixed_charge_per_kw, pg_surcharge, fppca, duty_rate, gruha_jyothi_cap, dg_rate_min, dg_rate_max, effective_from)
values (1, 'LT-1 Domestic', 5.80, 150, 0.35, 0.38, 0.09, 200, 18, 25, '2026-04-01')
on conflict (id) do update set energy_rate = excluded.energy_rate, fixed_charge_per_kw = excluded.fixed_charge_per_kw,
  pg_surcharge = excluded.pg_surcharge, fppca = excluded.fppca, duty_rate = excluded.duty_rate;

insert into maintenance_notices (subdivision_id, weekday, window_start, window_end, note)
select id, 2, '10:00', '17:00', 'Routine feeder and transformer maintenance. Timing varies by circular.' from bescom_subdivisions
where outage_risk_level in ('medium', 'high')
on conflict do nothing;
`;
fs.writeFileSync('backend/sql/seed.sql', '-- generated by scripts/gen-data.mjs, illustrative figures only\n' + sql + '\n' + rest);
console.log('ok', out.length);
