
import React,{useEffect,useState} from 'react'; import {Text,View,Pressable,ScrollView} from 'react-native'; import * as DocumentPicker from 'expo-document-picker'; import {useApp} from '../AppContext';
import {createAppliance, deleteAppliance} from '../api'; import {APPLIANCE_PRESETS} from '../data'; import {Card,Button,Chip,Field,s} from '../components'; import {TARIFF,computeBill,inr,isOffPeak,hoursUntilOffPeak,monthlyUnits,parseIntervals,runtimeMinutes} from '../utils';
export default function Appliances(){const {appliances,setAppliances,settings,unitsSoFar,meterUnits,setMeterUnits,setIntervals,monthKey,alerts,setAlerts,askNotifications}=useApp();const [paste,setPaste]=useState('');const [msg,setMsg]=useState('');const [,tick]=useState(0);useEffect(()=>{const i=setInterval(()=>tick(x=>x+1),20000);return()=>clearInterval(i)},[]);
const add=async p=>{const local={...p,id:`${Date.now()}-${Math.random()}`,startedAt:null,alerted:false,alertAfter:35}; try{const remote=await createAppliance({name:p.name,watts:p.watts,dailyRuntimeHours:p.hoursPerDay,alertAfterMinutes:35}); setAppliances(x=>[...x,{...local,id:remote.id}]);}catch{setAppliances(x=>[...x,local]);}};const patch=(id,c)=>setAppliances(x=>x.map(a=>a.id===id?{...a,...c}:a));const toggle=a=>patch(a.id,a.startedAt?{startedAt:null,alerted:false}:{startedAt:Date.now(),alerted:false});const estimate=monthlyUnits(appliances),projected=Math.max(unitsSoFar,estimate),bill=computeBill({units:projected,sanctionedKw:settings.sanctionedKw,gruhaJyothi:settings.gruhaJyothi});
async function pick(){const r=await DocumentPicker.getDocumentAsync({type:['text/*','text/csv'],copyToCacheDirectory:true});if(!r.canceled){const f=r.assets[0];setPaste(await (await fetch(f.uri)).text())}}
function ingest(){const r=parseIntervals(paste);if(!r.count)return setMsg('No 15-minute readings found.');setIntervals({...r,month:monthKey()});setMsg(`Loaded ${r.count} readings, ${r.total} kWh, peak draw about ${r.peakKw} kW.`);setPaste('')}
return <><Card title="Month so far"><Field label="Units on your meter this month" value={meterUnits} onChangeText={setMeterUnits} keyboardType="numeric"/><Text style={s.text}>Using <Text style={{fontWeight:'800'}}>{Math.round(unitsSoFar)}</Text> units; appliances add about <Text style={{fontWeight:'800'}}>{estimate}</Text> units/month. Projected bill: <Text style={{fontWeight:'800'}}>{inr(bill.payable)}</Text>.</Text>{settings.gruhaJyothi&&<><View style={s.progress}><View style={[s.progressFill,{width:`${Math.min(100,projected/TARIFF.gruhaJyothiCap*100)}%`}]}/></View><Text style={s.muted}>Alert at {TARIFF.gruhaJyothiWarn} units; subsidy ends after {TARIFF.gruhaJyothiCap}.</Text></>}<Button title="Enable device alerts" onPress={askNotifications}/></Card>
<Card title="High-draw appliances"><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:7}}>{APPLIANCE_PRESETS.map(p=><Chip key={p.name} title={`+ ${p.name}`} onPress={()=>add(p)}/>)}</ScrollView>{!appliances.length&&<Text style={s.muted}>Add an appliance, then tap Start when you switch it on.</Text>}{appliances.map(a=><View key={a.id} style={s.row}><View style={{flex:1}}><Text style={{fontWeight:'750',color:'#14213D'}}>{a.name}</Text><Text style={s.muted}>{a.watts} W · {a.startedAt?`Running ${runtimeMinutes(a)} min`:'Off'} · {a.hoursPerDay} h/day</Text></View><View style={s.rowActions}><Text style={s.muted}>h</Text><Field value={a.hoursPerDay} onChangeText={v=>patch(a.id,{hoursPerDay:Number(v)||0})} keyboardType="numeric"/><Button title={a.startedAt?'Stop':'Start'} danger={!!a.startedAt} onPress={()=>toggle(a)}/><Pressable onPress={async()=>{await deleteAppliance(a.id).catch(()=>{});setAppliances(x=>x.filter(q=>q.id!==a.id))}}><Text style={s.link}>Remove</Text></Pressable></View></View>)}</Card>
{appliances.some(a=>a.ev)&&<Card title="EV charging window"><Text style={s.text}>{isOffPeak()?'It is off-peak now (10 PM–6 AM). Good time to charge.':`Peak hours. Off-peak starts in about ${hoursUntilOffPeak()} h, at 10 PM.`}</Text></Card>}
<Card title="Smart meter readings (15 min)"><Field label="Paste CSV rows" value={paste} onChangeText={setPaste} placeholder={'2026-09-01 00:00,0.20\\n2026-09-01 00:15,0.55'}/><View style={{flexDirection:'row',gap:8}}><Button title="Choose CSV" secondary onPress={pick}/><Button title="Load readings" disabled={!paste.trim()} onPress={ingest}/></View>{msg&&<Text style={s.text}>{msg}</Text>}</Card>
<Card title="Recent alerts">{!alerts.length&&<Text style={s.muted}>Nothing yet.</Text>}{alerts.map(a=><View key={a.id} style={s.alert}><Text style={{fontWeight:'750'}}>{a.title}</Text><Text style={s.text}>{a.body}</Text><Text style={s.muted}>{new Date(a.at).toLocaleString('en-IN')}</Text></View>)}{!!alerts.length&&<Pressable onPress={()=>setAlerts([])}><Text style={s.link}>Clear alerts</Text></Pressable>}</Card></>}
